package com.arduia.expense.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object ProArtboard {
    const val PIXEL_9_PRO_WIDTH_DP = 427
    const val PIXEL_9_PRO_HEIGHT_DP = 952
    const val SPEC_CAPTURE_WIDTH_DP = 1100
    const val SPEC_CAPTURE_HEIGHT_DP = 800
}

@Immutable
data class ProButtonSize(
    val height: Dp,
    val horizontalPadding: Dp,
    val verticalPadding: Dp,
    val fontSizeSp: Float,
    val radius: Dp,
)

@Immutable
data class ProDimens(
    val space2: Dp,
    val space4: Dp,
    val space6: Dp,
    val space7: Dp,
    val space8: Dp,
    val space10: Dp,
    val space12: Dp,
    val space14: Dp,
    val space16: Dp,
    val space18: Dp,
    val space20: Dp,
    val space24: Dp,
    val space26: Dp,
    val space28: Dp,
    val space32: Dp,
    val space38: Dp,
    val space44: Dp,
    val buttonFilledHeight: Dp,
    val buttonOutlinedHeight: Dp,
    val buttonSmallHeight: Dp,
    val buttonSm: ProButtonSize,
    val buttonMd: ProButtonSize,
    val buttonLg: ProButtonSize,
    val iconNav: Dp,
    val iconInline: Dp,
    val iconChipLeading: Dp,
    val iconTag: Dp,
    val iconClear: Dp,
    val iconBadge: Dp,
    val cardRadius: Dp,
    val cardPadding: Dp,
    val chipRadius: Dp,
    val tileRadius: Dp,
    val sheetRadiusTop: Dp,
    val sheetMaxHeightFraction: Float,
    val fabSize: Dp,
    val touchTargetMin: Dp,
    val artboardWidth: Dp,
    val artboardHeight: Dp,
    val buttonBorderWidth: Dp,
    val chipBorderWidth: Dp,
    val sheetHandleWidth: Dp,
    val sheetHandleHeight: Dp,
    val navCornerRadius: Dp,
    val navBarHeight: Dp,
    val navItemPaddingVertical: Dp,
    val navFabOffset: Dp,
    val navFabProtrusion: Dp,
    val navShellBottomInset: Dp,
    val navSurfaceAlpha: Float,
    val quickAccessIconSize: Dp,
    val quickAccessIconGlyph: Dp,
    val keypadKeyRadius: Dp,
    val rowPaddingH: Dp,
    val rowPaddingV: Dp,
    val screenPadding: Dp,
    val emptyIllustrationWidth: Dp,
    val emptyIllustrationHeight: Dp,
    val addHintChipSize: Dp,
    val addHintIconSize: Dp,
    val onboardingIllustrationSize: Dp,
    val pageIndicatorActiveWidth: Dp,
    val pageIndicatorDotSize: Dp,
    val onboardingNavBottomMargin: Dp,
    val profileStepBarWidth: Dp,
    val profileStepBarHeight: Dp,
    val currencySymbolSize: Dp,
)

val LocalProDimens = staticCompositionLocalOf { ProDefaultDimens }

val ProDefaultDimens = ProDimens(
    space2 = 2.dp,
    space4 = 4.dp,
    space6 = 6.dp,
    space7 = 7.dp,
    space8 = 8.dp,
    space10 = 10.dp,
    space12 = 12.dp,
    space14 = 14.dp,
    space16 = 16.dp,
    space18 = 18.dp,
    space20 = 20.dp,
    space24 = 24.dp,
    space26 = 26.dp,
    space28 = 28.dp,
    space32 = 32.dp,
    space38 = 38.dp,
    space44 = 44.dp,
    buttonFilledHeight = 52.dp,
    buttonOutlinedHeight = 48.dp,
    buttonSmallHeight = 36.dp,
    buttonSm = ProButtonSize(
        height = 36.dp,
        horizontalPadding = 14.dp,
        verticalPadding = 8.dp,
        fontSizeSp = 12f,
        radius = 10.dp,
    ),
    buttonMd = ProButtonSize(
        height = 48.dp,
        horizontalPadding = 18.dp,
        verticalPadding = 12.dp,
        fontSizeSp = 14f,
        radius = 12.dp,
    ),
    buttonLg = ProButtonSize(
        height = 52.dp,
        horizontalPadding = 22.dp,
        verticalPadding = 16.dp,
        fontSizeSp = 15f,
        radius = 14.dp,
    ),
    iconNav = 25.dp,
    iconInline = 16.dp,
    iconChipLeading = 14.dp,
    iconTag = 10.dp,
    iconClear = 15.dp,
    iconBadge = 38.dp,
    cardRadius = 16.dp,
    cardPadding = 18.dp,
    chipRadius = 999.dp,
    tileRadius = 14.dp,
    sheetRadiusTop = 22.dp,
    sheetMaxHeightFraction = 0.78f,
    fabSize = 64.dp,
    touchTargetMin = 44.dp,
    artboardWidth = ProArtboard.PIXEL_9_PRO_WIDTH_DP.dp,
    artboardHeight = ProArtboard.PIXEL_9_PRO_HEIGHT_DP.dp,
    buttonBorderWidth = 1.4.dp,
    chipBorderWidth = 1.2.dp,
    sheetHandleWidth = 36.dp,
    sheetHandleHeight = 4.dp,
    navCornerRadius = 8.dp,
    navBarHeight = 72.dp,
    navItemPaddingVertical = 8.dp,
    navFabOffset = 60.dp,
    navFabProtrusion = 4.dp,
    navShellBottomInset = 140.dp,
    navSurfaceAlpha = 0.86f,
    quickAccessIconSize = 36.dp,
    quickAccessIconGlyph = 18.dp,
    keypadKeyRadius = 12.dp,
    rowPaddingH = 8.dp,
    rowPaddingV = 12.dp,
    screenPadding = 22.dp,
    emptyIllustrationWidth = 180.dp,
    emptyIllustrationHeight = 140.dp,
    addHintChipSize = 20.dp,
    addHintIconSize = 12.dp,
    onboardingIllustrationSize = 280.dp,
    pageIndicatorActiveWidth = 22.dp,
    pageIndicatorDotSize = 6.dp,
    onboardingNavBottomMargin = 48.dp,
    profileStepBarWidth = 28.dp,
    profileStepBarHeight = 4.dp,
    currencySymbolSize = 36.dp,
)
