#!/bin/bash
#
# Regenerate the codebase reference snapshot at .cursor/context/project_codebase.md.
#
# Invoked automatically at the end of an agent turn by the Claude `Stop` hook
# (.claude/settings.json -> .claude/hooks/update-codebase.sh) and the Cursor `stop`
# hook (.cursor/hooks.json -> .cursor/hooks/update-codebase.sh).
#
# The snapshot is fully derived from the repo (modules, namespaces, counts, screen
# specs, key files) so it stays accurate. Content is deterministic and the file is
# only rewritten when the structural body changes — re-running on an unchanged tree
# is a no-op (the "Last updated" date only advances when something actually changed).
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

SNAPSHOT=".cursor/context/project_codebase.md"
SETTINGS="settings.gradle.kts"

# Nothing to generate without the Gradle module list.
[ -f "${SETTINGS}" ] || exit 0

branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"

count() { printf '%s' "$(grep -c . <<<"$1" 2>/dev/null || echo 0)"; }
files_count() { find $1 -type f -name "$2" 2>/dev/null | wc -l | tr -d ' '; }

# --- Gradle modules (in settings.gradle.kts order) + namespace per module ----------
module_paths="$(grep -E '^\s*include\(' "${SETTINGS}" | grep -oE '":[^"]+"' | tr -d '"')"

module_rows=""
feature_rows=""
module_total=0
feature_total=0
while IFS= read -r path; do
    [ -n "${path}" ] || continue
    module_total=$((module_total + 1))
    dir="${path#:}"; dir="${dir//://}"
    bg="${dir}/build.gradle.kts"
    ns="$(grep -m1 -oE 'namespace = "[^"]+"' "${bg}" 2>/dev/null | sed -E 's/namespace = "([^"]+)"/\1/')"
    [ -n "${ns}" ] || ns="—"
    module_rows+="| \`${path}\` | \`${ns}\` |"$'\n'
    case "${path}" in
        :feature:*)
            feature_total=$((feature_total + 1))
            feature_rows+="- \`${path}\`"$'\n'
            ;;
    esac
done <<<"${module_paths}"

# --- Counts ------------------------------------------------------------------------
screen_specs="$(find design-system-spec/screens -type f -name '*.md' ! -name 'README.md' 2>/dev/null | wc -l | tr -d ' ')"
baselines="$(files_count app/src/test/screenshots '*.png')"
app_tests="$(files_count app/src/test '*.kt')"
composable_files="$(grep -rlE '@Composable' --include=*.kt feature shared app 2>/dev/null | grep -v '/build/' | wc -l | tr -d ' ')"

# --- Screen specs list -------------------------------------------------------------
screens_list=""
while IFS= read -r f; do
    [ -n "${f}" ] || continue
    screens_list+="- \`$(basename "${f}")\`"$'\n'
done <<<"$(find design-system-spec/screens -type f -name '*.md' ! -name 'README.md' 2>/dev/null | sort)"
[ -n "${screens_list}" ] || screens_list="- (none)"$'\n'

# --- Key files (emit only those present) -------------------------------------------
emit_keyfile() { [ -e "$1" ] && printf '| `%s` | %s |\n' "$1" "$2" || true; }
key_rows=""
key_rows+="$(emit_keyfile "settings.gradle.kts" "Gradle module graph")"$'\n'
key_rows+="$(emit_keyfile "app/build.gradle.kts" "App module — flavors (dev/production), deps, test config")"$'\n'
key_rows+="$(emit_keyfile "gradle/libs.versions.toml" "Version catalog")"$'\n'
key_rows+="$(emit_keyfile "AGENTS.md" "Authoritative agent instructions")"$'\n'
key_rows+="$(emit_keyfile "docs/module_structure.md" "Module map & dependency rules")"$'\n'
key_rows+="$(emit_keyfile "design-system-spec/tokens.md" "Design tokens (authoritative)")"$'\n'
key_rows+="$(emit_keyfile "design-system-spec/screen-specs.js" "Screen spec viewer data")"$'\n'
key_rows+="$(emit_keyfile "scripts/setup-android-toolchain.sh" "One-time toolchain setup")"$'\n'

# --- Render to a temp file with a date placeholder ---------------------------------
tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT

{
cat <<EOF
# Pro Expense — Codebase Snapshot

> Auto-generated by \`scripts/update-codebase-snapshot.sh\` (Claude \`Stop\` / Cursor \`stop\` hook).
> Do not edit by hand — it is overwritten. Authoritative prose lives in \`AGENTS.md\` and \`docs/\`.

- **Last updated:** @@DATE@@
- **Branch:** \`${branch}\`
- **Stack:** Kotlin Multiplatform · Jetpack Compose (Android) · offline-first
- **PR base (v2 migration):** PRs target \`refactor/v2-migration\` until the migration completes — not \`main\`.

---

## Modules

| Module | Namespace |
|--------|-----------|
${module_rows}
## Feature modules (MVP)

${feature_rows}
## At a glance

| Metric | Count |
|--------|------:|
| Gradle modules | ${module_total} |
| Feature modules | ${feature_total} |
| Screen specs (\`design-system-spec/screens/\`) | ${screen_specs} |
| Roborazzi baselines (\`app/src/test/screenshots/\`) | ${baselines} |
| App test sources (\`app/src/test/\`) | ${app_tests} |
| Files with \`@Composable\` | ${composable_files} |

## Screen specs

${screens_list}
## Key files

| File | Role |
|------|------|
${key_rows}
## Conventions (see \`AGENTS.md\` for authority)

- Architecture: Compose/SwiftUI → ViewModel → \`feature:*\` repository contracts (KMP \`commonMain\`) → \`core:data\` → platform storage.
- Features never depend on other features — they compose only at the \`app\` / UI layer.
- Amounts stored as integer ×100 (\`core:domain\`).
- Default flavor \`devDebug\`; verify with \`./gradlew verifyAll\`.
- UI changes: \`@Preview\` per state + green Roborazzi baseline before push.
EOF
} > "${tmp}"

# --- Write only when the body (everything except the date line) changed ------------
strip_date() { grep -v 'Last updated:' "$1" 2>/dev/null || true; }
if [ -f "${SNAPSHOT}" ] && diff -q <(strip_date "${SNAPSHOT}") <(strip_date "${tmp}") >/dev/null 2>&1; then
    exit 0
fi

sed "s/@@DATE@@/$(date +%F)/" "${tmp}" > "${SNAPSHOT}"
exit 0
